Entering certain systems (it seemed to be binary ones) caused Pioneer to crash with this message:
error: [string "[T] @pigui/game.lua"]:674: invalid order function for sorting
stack traceback:
	[C]: in function 'sort'
	[string "[T] @pigui/game.lua"]:674: in function 'displayOnScreenObjects'
	[string "[T] @pigui/game.lua"]:746: in function 'fun'
	[string "[T] @pigui/pigui.lua"]:42: in function 'window'
	[string "[T] @pigui/game.lua"]:739: in function 'fun'
	[string "[T] @pigui/pigui.lua"]:71: in function 'withStyleColors'
	[string "[T] @pigui/game.lua"]:738: in function 'game'
	[string "[T] @pigui/pigui.lua"]:83: in function <[string "[T] @pigui/pigui.lua"]:81>

I haven't coded in Lua before, but it seems the error is regarding the sorting function.
A quick google search revealed the sorting function should return false when the items are equal.

I've reordered the cases in "l_body_is_more_important_than" and this seems to resolve the issue.