Error on non-existing translations.
Add missing token PASSENGER_CABIN to equipment-core.

Use l:get from now on to get the translation or nil (no error if an entry
doesn't exist)

If a translation doesn't exist, the missing token and the resource and language
code it was supposed to be in are shown:

error: [string "[T] @modules/CrewContracts/CrewContracts.lua"]:402: missing translation token: `NAVIGATOR' in resource `module-crewcontracts', language code `en'.
stack traceback:
	[C]: in function '__index'
	[string "[T] @modules/CrewContracts/CrewContracts.lua"]:402: in function 'cb'
	[string "[T] @libs/Event.lua"]:34: in function '?'
	[string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>